# CQ3 – What are is the measurement value for a specific cytokine from a specific patient in a specific measurement process?

PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>
PREFIX sio:     <http://semanticscience.org/resource/>
PREFIX bco:     <http://purl.org/beat-covid/cytokines-semantic-model.owl#>

ASK WHERE {
    ?person a sio:SIO_000498;
              sio:SIO_000228 ?person_study_role .

    ?person_study_role a sio:SIO_000883 ;
                         sio:SIO_000356 ?measurement_process .

    ?person_study_id a bco:beat_covid_id ;
                  sio:SIO_000300 ?person_study_idstring ;
                  obo:IAO_0000219 ?person_study_role .

    ?measurement_process a obo:OBI_0000070 ;
                           sio:SIO_000291 ?trait_cytokine ;
                           sio:SIO_000229 ?quantitative_trait ;
                           sio:SIO_000008 ?measurement_process_date .

    ?measurement_process_date a obo:NCIT_C25164 ; 
                                dc:Date ?measurement_process_date_value . 

    ?quantitative_trait a obo:IAO_0000109 .

    ?trait_cytokine a sio:SIO_010043 ;
                      sio:SIO_000300 ?cytokine_idstring ;
                      sio:SIO_010079 ?cytokine ;
                      sio:SIO_000216 ?quantitative_trait .

    ?cytokine a sio:SIO_010035 .

    ?quantitative_trait sio:SIO_000300 ?measurement_value .

    FILTER isLiteral(?person_study_idstring)
    FILTER isLiteral(?cytokine_idstring)
}
